kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx4g
kotlin.native.ignoreDisabledTargets=true
kotlin.caching.enabled=true
kotlin.incremental=true
org.gradle.jvmargs=-Xmx4g -XX:+UseParallelGC -Dfile.encoding=UTF-8
org.gradle.configuration-cache=true
org.gradle.caching=true
android.nonTransitiveRClass=true
android.useAndroidX=true
# Workaround AGP 9.0+: com.android.library incompatible con kotlin.multiplatform
android.builtInKotlin=false
android.newDsl=false
